"""Rebuild the offline review bank from the structured daily lesson content."""
import html
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
# One unambiguous, prompted word from each lesson's five example sentences.
GAPS = {
    1: "as part responsibility with help",
    2: "by first After often end",
    3: "currently now focusing well deadline",
    4: "use collaborate track share unclear",
    5: "finished going still blocker from",
    6: "going almost trouble Could together",
    8: "issue when noticed affects expected",
    9: "symptom takes result means impact",
    10: "caused possibility sure whether probably",
    11: "already First Then solve yet",
    12: "clarify show Which when check",
    13: "option Another advantage downside recommend",
    15: "think opinion view because For",
    16: "reason because example good why",
    17: "agree point mean sure instead",
    18: "Compared more Both difference better",
    19: "decided chose reason considered Although",
    20: "question mean example yet back",
    22: "Last completed found Friday result",
    23: "First Next After Then Finally",
    24: "learned lesson Looking time experience",
    25: "going plan meeting goal By",
    26: "will expect probably may confident",
    27: "completed far track still step",
}


def plain(value):
    return html.unescape(re.sub(r"<[^>]+>", "", value)).strip()


bank = {}
for week in range(1, 5):
    chunks = []
    for day in range(week * 7 - 6, week * 7):
        lesson = json.loads((ROOT / f"src/content/lessons/day-{day:02}.json").read_text())
        cards = next(section["items"] for section in lesson["sections"] if section["type"] == "chunks")
        assert len(cards) == 5
        for i, (card, gap) in enumerate(zip(cards, GAPS[day].split()), 1):
            use, pattern, simple, model = card["details"]
            prompt, count = re.subn(rf"\b{gap}\b", "_____", simple, count=1)
            assert count == 1, (day, gap, simple)
            chunks.append({
                "id": f"d{day}-c{i}", "day": day,
                "chunk": card["phrase"],
                "meaning": card["meaning"],
                "situation": use, "pattern": pattern, "model": model,
                "gap": prompt, "answer": gap, "simple": simple,
            })
    # Each five-question block visits different days of the week.
    bank[week] = [chunks[day * 5 + chunk] for chunk in range(5) for day in range(6)]

output = "// Generated by scripts/build-weekly-review.py; edit src/content/lessons for content.\n"
output += "window.SpeakSprintReviewBank = " + json.dumps(bank, ensure_ascii=False, indent=2) + ";\n"
(ROOT / "public/assets/weekly-review-data.js").write_text(output)
print("Built 4 weekly banks: 30 chunks and 90 exercises per week.")
